version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - /
      - /netsnmp
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
