---
run:
  timeout: 5m

linters:
  enable:
  - bodyclose
  - copyloopvar
  - dogsled
  - dupl
  - gochecknoglobals
  - goconst
  - gocritic
  - goimports
  - goprintffuncname
  - gosec
  - misspell
  - nakedret
  - nolintlint
  - revive # Replaces golint
  - unconvert
  - unparam
  - whitespace
  # TODO the following linters
  # - gocognit
  # - gocyclo
  # - goerr113
  # - gomnd
  # - lll
  # - nestif
  # - prealloc

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 20
  govet:
    enable:
    - shadow

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - gochecknoglobals
    - nolintlint
