// Code generated by "stringer -type=SnmpV3SecurityModel"; DO NOT EDIT.

package gosnmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserSecurityModel-3]
}

const _SnmpV3SecurityModel_name = "UserSecurityModel"

var _SnmpV3SecurityModel_index = [...]uint8{0, 17}

func (i SnmpV3SecurityModel) String() string {
	idx := int(i) - 3
	if i < 3 || idx >= len(_SnmpV3SecurityModel_index)-1 {
		return "SnmpV3SecurityModel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SnmpV3SecurityModel_name[_SnmpV3SecurityModel_index[idx]:_SnmpV3SecurityModel_index[idx+1]]
}
