// Copyright 2026 The GoSNMP Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

//go:build all || marshal

package gosnmp

import (
	_ "embed"
	"encoding/base64"
	"fmt"
	"strings"
)

// The harness replays complete REPORT messages generated by libsnmp. Fixed
// identifiers let tests use the packets unchanged, including the authenticated
// fixture whose HMAC covers both identifiers.

//go:embed testdata/v3_harness/unknown_engine_ids_report.b64
var v3UnknownEngineIDsReportBase64 string

//go:embed testdata/v3_harness/not_in_time_windows_report_sha1.b64
var v3NotInTimeWindowsReportBase64 string

type v3HarnessFixture struct {
	name      string
	base64    string
	msgID     uint32
	requestID uint32
}

var (
	v3UnknownEngineIDsReportFixture = v3HarnessFixture{
		name:      "unknownEngineIDs REPORT",
		base64:    v3UnknownEngineIDsReportBase64,
		msgID:     170000001,
		requestID: 270000001,
	}
	v3NotInTimeWindowsReportFixture = v3HarnessFixture{
		name:      "notInTimeWindows REPORT",
		base64:    v3NotInTimeWindowsReportBase64,
		msgID:     170000101,
		requestID: 270000101,
	}
)

func (f v3HarnessFixture) decode() ([]byte, error) {
	packet, err := base64.StdEncoding.DecodeString(strings.TrimSpace(f.base64))
	if err != nil {
		return nil, fmt.Errorf("decoding %s fixture: %w", f.name, err)
	}
	if len(packet) == 0 {
		return nil, fmt.Errorf("decoding %s fixture: empty packet", f.name)
	}
	return packet, nil
}

// seedIDs sets the counters to one below the fixture values because the send
// path increments each counter before marshaling a request. Connect must have
// completed first because it initializes both counters.
func (f v3HarnessFixture) seedIDs(gs *GoSNMP) {
	gs.SetMsgID(f.msgID - 1)
	gs.SetRequestID(f.requestID - 1)
}
