// Copyright 2026 The GoSNMP Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.

//go:build all || marshal || trap

package gosnmp

// v3TestAgent is a scripted loopback SNMPv3 agent for exercising the client's
// v3 send/receive path against controlled responses. Every incoming message
// is parsed, verified (HMAC/username, when the message claims authentication),
// appended to a request log, and handed to the next step of a per-test script.
// A step returns zero or more raw messages to send back; returning nothing
// drops the request so the client retries or times out.
//
// Responses can be built two ways:
//   - a.reply(...) marshals an ordinary conforming response at the agent's
//     configured security level with the library's own marshaling;
//   - committed libsnmp-generated bytes are replayed for REPORTs, keeping the
//     fixture encoding and authentication independent of the code under test.

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"sync"
	"sync/atomic"
	"testing"
)

// v3TestAgentCreds is the single USM user the agent accepts and replies as.
type v3TestAgentCreds struct {
	username  string
	authProto SnmpV3AuthProtocol
	authPass  string
	privProto SnmpV3PrivProtocol // AES family only; DES reply salts are unsupported
	privPass  string
}

// v3TestAgentRequest is one received message: the pristine wire bytes and the
// parsed (decrypted, MAC-verified) packet.
type v3TestAgentRequest struct {
	Raw    []byte
	Packet *SnmpPacket
}

// v3TestAgentStep handles the n-th received request and returns the raw
// messages to send in reply. nil means drop.
type v3TestAgentStep func(req *v3TestAgentRequest) [][]byte

// v3TestAgent serves exactly one transport: start it with either startUDP or
// startTCP, never both.
type v3TestAgent struct {
	engineID   string
	boots      uint32
	engineTime uint32
	creds      v3TestAgentCreds
	secretKey  []byte
	privacyKey []byte
	logger     Logger

	steps []v3TestAgentStep

	udpConn *net.UDPConn
	tcpList net.Listener

	mu       sync.Mutex
	requests []*v3TestAgentRequest
	tcpConns []net.Conn
	saltCtr  uint64

	connWG sync.WaitGroup
	errs   chan error
	done   chan struct{}
}

//nolint:unparam // boots varies per test scenario, not per current caller
func newV3TestAgent(t *testing.T, engineID string, boots, engineTime uint32, creds v3TestAgentCreds) *v3TestAgent {
	t.Helper()
	a := &v3TestAgent{
		engineID:   engineID,
		boots:      boots,
		engineTime: engineTime,
		creds:      creds,
		logger:     NewLogger(log.New(io.Discard, "", 0)),
		errs:       make(chan error, 16),
		done:       make(chan struct{}),
	}
	var err error
	if creds.authProto > NoAuth {
		a.secretKey, err = genlocalkey(creds.authProto, creds.authPass, engineID)
		if err != nil {
			t.Fatalf("localizing agent auth key: %v", err)
		}
	}
	if creds.privProto > NoPriv {
		a.privacyKey, err = genlocalPrivKey(creds.privProto, creds.authProto, creds.privPass, engineID)
		if err != nil {
			t.Fatalf("localizing agent priv key: %v", err)
		}
	}
	return a
}

// startUDP binds a loopback UDP socket, starts serving, and returns the port.
// Shutdown and error collection are registered via t.Cleanup.
func (a *v3TestAgent) startUDP(t *testing.T) uint16 {
	t.Helper()
	if a.udpConn != nil || a.tcpList != nil {
		t.Fatal("v3TestAgent serves one transport; already started")
	}
	conn, err := net.ListenUDP("udp", &net.UDPAddr{IP: net.ParseIP("127.0.0.1")})
	if err != nil {
		t.Fatalf("v3TestAgent listen udp: %v", err)
	}
	a.udpConn = conn
	go a.serveUDP()
	t.Cleanup(func() { a.closeAndCheck(t) })
	return uint16(conn.LocalAddr().(*net.UDPAddr).Port) //nolint:gosec
}

// startTCP binds a loopback TCP listener, starts serving, and returns the port.
func (a *v3TestAgent) startTCP(t *testing.T) uint16 {
	t.Helper()
	if a.udpConn != nil || a.tcpList != nil {
		t.Fatal("v3TestAgent serves one transport; already started")
	}
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("v3TestAgent listen tcp: %v", err)
	}
	a.tcpList = lis
	go a.serveTCP()
	t.Cleanup(func() { a.closeAndCheck(t) })
	return uint16(lis.Addr().(*net.TCPAddr).Port) //nolint:gosec
}

func (a *v3TestAgent) serveUDP() {
	defer close(a.done)
	buf := make([]byte, rxBufSize)
	for {
		n, addr, err := a.udpConn.ReadFromUDP(buf)
		if err != nil {
			return
		}
		for _, out := range a.handle(buf[:n]) {
			if _, err = a.udpConn.WriteToUDP(out, addr); err != nil {
				a.sendErr(fmt.Errorf("WriteToUDP: %w", err))
			}
		}
	}
}

func (a *v3TestAgent) serveTCP() {
	defer close(a.done)
	for {
		conn, err := a.tcpList.Accept()
		if err != nil {
			return
		}
		a.mu.Lock()
		a.tcpConns = append(a.tcpConns, conn)
		a.mu.Unlock()
		a.connWG.Add(1)
		go a.serveTCPConn(conn)
	}
}

// serveTCPConn reads one BER-framed SNMP message at a time from the stream,
// tolerating fragmented or coalesced reads, and answers each with the
// scripted step's replies.
func (a *v3TestAgent) serveTCPConn(conn net.Conn) {
	defer a.connWG.Done()
	defer conn.Close()
	r := bufio.NewReader(conn)
	for {
		msg, err := readBERMessage(r)
		if err != nil {
			if !errors.Is(err, io.EOF) && !errors.Is(err, net.ErrClosed) {
				a.sendErr(fmt.Errorf("tcp read: %w", err))
			}
			return
		}
		for _, out := range a.handle(msg) {
			if _, err = conn.Write(out); err != nil {
				a.sendErr(fmt.Errorf("tcp write: %w", err))
			}
		}
	}
}

// readBERMessage reads exactly one definite-length BER SEQUENCE (tag, length
// octets, payload) from r, leaving any following bytes for the next call.
// It returns io.EOF only when the stream ends cleanly between messages.
func readBERMessage(r *bufio.Reader) ([]byte, error) {
	tag, err := r.ReadByte()
	if err != nil {
		return nil, err
	}
	if tag != 0x30 {
		return nil, fmt.Errorf("message does not start with a SEQUENCE tag: 0x%02x", tag)
	}
	first, err := r.ReadByte()
	if err != nil {
		return nil, fmt.Errorf("reading BER length: %w", noEOF(err))
	}
	header := []byte{tag, first}
	length := int(first)
	if first&0x80 != 0 {
		n := int(first & 0x7f)
		if n == 0 || n > 3 {
			return nil, fmt.Errorf("unsupported BER length form 0x%02x", first)
		}
		lenBytes := make([]byte, n)
		if _, err = io.ReadFull(r, lenBytes); err != nil {
			return nil, fmt.Errorf("reading BER length: %w", noEOF(err))
		}
		header = append(header, lenBytes...)
		length = 0
		for _, b := range lenBytes {
			length = length<<8 | int(b)
		}
	}
	if length > rxBufSize {
		return nil, fmt.Errorf("BER length %d exceeds %d", length, rxBufSize)
	}
	msg := make([]byte, len(header)+length)
	copy(msg, header)
	if _, err = io.ReadFull(r, msg[len(header):]); err != nil {
		return nil, fmt.Errorf("reading BER payload: %w", noEOF(err))
	}
	return msg, nil
}

// noEOF converts a mid-message io.EOF into io.ErrUnexpectedEOF so a stream
// truncated inside a message is reported instead of reading as a clean close.
func noEOF(err error) error {
	if errors.Is(err, io.EOF) {
		return io.ErrUnexpectedEOF
	}
	return err
}

// handle parses and logs one incoming message and runs the next scripted step.
func (a *v3TestAgent) handle(raw []byte) [][]byte {
	pristine := bytes.Clone(raw)
	pkt, err := a.parse(raw)
	if err != nil {
		a.sendErr(fmt.Errorf("parsing request: %w", err))
		return nil
	}
	req := &v3TestAgentRequest{Raw: pristine, Packet: pkt}

	a.mu.Lock()
	idx := len(a.requests)
	a.requests = append(a.requests, req)
	var step v3TestAgentStep
	if idx < len(a.steps) {
		step = a.steps[idx]
	}
	a.mu.Unlock()

	if step == nil {
		a.sendErr(fmt.Errorf("no scripted step for request %d", idx))
		return nil
	}
	return step(req)
}

// parse decodes an incoming message with the library's own parser and, when
// the message claims authentication, verifies its HMAC and username against
// the agent's configured user.
func (a *v3TestAgent) parse(raw []byte) (*SnmpPacket, error) {
	parser := &GoSNMP{Version: Version3, Logger: a.logger}
	pkt := &SnmpPacket{
		Logger: a.logger,
		SecurityParameters: &UsmSecurityParameters{
			AuthenticationProtocol:   a.creds.authProto,
			AuthenticationPassphrase: a.creds.authPass,
			PrivacyProtocol:          a.creds.privProto,
			PrivacyPassphrase:        a.creds.privPass,
			Logger:                   a.logger,
		},
	}

	buf := bytes.Clone(raw)
	cursor, err := parser.unmarshalHeader(buf, pkt)
	if err != nil {
		return nil, fmt.Errorf("unmarshalHeader: %w", err)
	}

	usp := pkt.SecurityParameters.(*UsmSecurityParameters)
	if pkt.MsgFlags&AuthNoPriv > 0 {
		if usp.UserName != a.creds.username {
			return nil, fmt.Errorf("authenticated request for unknown user %q", usp.UserName)
		}
		// unmarshalHeader blanked the MAC field in buf and stored the received
		// MAC in usp.AuthenticationParameters, so isAuthentic recomputes over
		// the correct bytes.
		authentic, err2 := usp.isAuthentic(buf, pkt)
		if err2 != nil {
			return nil, fmt.Errorf("isAuthentic: %w", err2)
		}
		if !authentic {
			return nil, fmt.Errorf("request HMAC verification failed")
		}
	}

	decrypted, cursor, err := parser.decryptPacket(buf, cursor, pkt)
	if err != nil {
		return nil, fmt.Errorf("decryptPacket: %w", err)
	}
	if err = parser.unmarshalPayload(decrypted, cursor, pkt); err != nil {
		return nil, fmt.Errorf("unmarshalPayload: %w", err)
	}
	return pkt, nil
}

// securityLevel is the level the agent replies at, from its configured user.
func (a *v3TestAgent) securityLevel() SnmpV3MsgFlags {
	switch {
	case a.creds.privProto > NoPriv:
		return AuthPriv
	case a.creds.authProto > NoAuth:
		return AuthNoPriv
	default:
		return NoAuthNoPriv
	}
}

// v3TestAgentReply describes a conforming response built by reply(). Nil
// override fields fall back to echoing the request (msgID, requestID) or to
// the agent's state (engine IDs, boots, engineTime); pointers keep zero and
// empty strings expressible, e.g. a Response carrying request-id 0 or a
// discovery REPORT carrying an empty context engine ID.
type v3TestAgentReply struct {
	pduType               PDUType
	vars                  []SnmpPDU
	msgID                 *uint32
	requestID             *uint32
	authoritativeEngineID *string
	contextEngineID       *string
	boots                 *uint32
	engineTime            *uint32
}

// reply builds and marshals a conforming response to req at the agent's
// security level. Marshal failures are reported through the error channel and
// produce no reply.
func (a *v3TestAgent) reply(req *v3TestAgentRequest, r v3TestAgentReply) [][]byte {
	msgID := req.Packet.MsgID
	if r.msgID != nil {
		msgID = *r.msgID
	}
	requestID := req.Packet.RequestID
	if r.requestID != nil {
		requestID = *r.requestID
	}
	authoritativeEngineID := a.engineID
	if r.authoritativeEngineID != nil {
		authoritativeEngineID = *r.authoritativeEngineID
	}
	contextEngineID := a.engineID
	if r.contextEngineID != nil {
		contextEngineID = *r.contextEngineID
	}
	boots := a.boots
	if r.boots != nil {
		boots = *r.boots
	}
	engineTime := a.engineTime
	if r.engineTime != nil {
		engineTime = *r.engineTime
	}
	sp := &UsmSecurityParameters{
		AuthoritativeEngineID:    authoritativeEngineID,
		AuthoritativeEngineBoots: boots,
		AuthoritativeEngineTime:  engineTime,
		UserName:                 a.creds.username,
		AuthenticationProtocol:   a.creds.authProto,
		PrivacyProtocol:          a.creds.privProto,
		SecretKey:                a.secretKey,
		PrivacyKey:               a.privacyKey,
		Logger:                   a.logger,
	}
	if a.creds.privProto > NoPriv {
		salt := make([]byte, 8)
		binary.BigEndian.PutUint64(salt, atomic.AddUint64(&a.saltCtr, 1))
		sp.PrivacyParameters = salt
	}
	pkt := &SnmpPacket{
		Version:            Version3,
		MsgFlags:           a.securityLevel(),
		SecurityModel:      UserSecurityModel,
		SecurityParameters: sp,
		PDUType:            r.pduType,
		MsgID:              msgID,
		RequestID:          requestID,
		ContextEngineID:    contextEngineID,
		Logger:             a.logger,
		Variables:          r.vars,
	}
	out, err := pkt.MarshalMsg()
	if err != nil {
		a.sendErr(fmt.Errorf("marshaling reply: %w", err))
		return nil
	}
	return [][]byte{out}
}

func (a *v3TestAgent) sendErr(err error) {
	select {
	case a.errs <- err:
	default:
	}
}

func (a *v3TestAgent) requestCount() int {
	a.mu.Lock()
	defer a.mu.Unlock()
	return len(a.requests)
}

func (a *v3TestAgent) request(i int) *v3TestAgentRequest {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.requests[i]
}

// closeAndCheck stops the agent and fails the test if the agent recorded any
// internal error (parse failure, failed HMAC, unscripted request, ...).
func (a *v3TestAgent) closeAndCheck(t *testing.T) {
	t.Helper()
	if a.udpConn != nil {
		a.udpConn.Close()
	}
	if a.tcpList != nil {
		a.tcpList.Close()
	}
	<-a.done
	a.mu.Lock()
	for _, c := range a.tcpConns {
		c.Close()
	}
	a.mu.Unlock()
	a.connWG.Wait()
	for {
		select {
		case err := <-a.errs:
			t.Errorf("v3TestAgent internal error: %v", err)
		default:
			return
		}
	}
}
