---
version: 2.1

executors:
  golang:
    docker:
      - image: busybox

jobs:
  noopjob:
    executor: golang

    steps:
      - run:
          command: "true"

workflows:
  version: 2
  noop:
    jobs:
      - noopjob
    triggers:
      - schedule:
          cron: "0 0 30 2 *"
          filters:
            branches:
              only:
                - main
